-- Run this in Supabase SQL Editor to bulk remove watched profiles
-- Go to: https://supabase.com/dashboard/project/nougobcvppzcnkjypqss/sql/new

DELETE FROM engagement_watched_profiles
WHERE prospect_id IN (
  SELECT id FROM prospects WHERE full_name IN (
    'Charles E. Gaudet II',
    'Harshida Acharya',
    'David Osterweil',
    'Penny Primus',
    'Joe Indig',
    'Heather Cheney',
    'Darpan Seth',
    'Pradeep Hegde',
    'Will Stokes',
    'Preston Rutherford',
    'Harish Abbott',
    'Kyle Hency',
    'Dave Wardell',
    'Daniel Anderson',
    'Luis Madrid',
    'Kiran Ramzi Mukunda',
    'Lucille DeHart',
    'Ray Bradbury',
    'Will Smith',
    'James Davis',
    'Jana Krekic',
    'Shanann Heaton',
    'Robert Brunner',
    'Heidi Robinson',
    'MichaelAaron Flicker',
    'Richard Shotton',
    'Tim den Heijer',
    'Yoni Kozminski',
    'Michael Barron',
    'Peter Theran',
    'Mark Schumacher',
    'Ahmad Nazir',
    'Ahmad Khan',
    'Lindsey Rosenberg',
    'Divia Singh',
    'Christa Locallo',
    'Paul Jurgensen',
    'Arianne Foulks',
    'Lyne Castonguay',
    'Eric Grunewald',
    'Andrew Faris',
    'Curtis Matsko',
    'Daniel Kasidi',
    'Kiran Patil',
    'Kieran McNeill',
    'Therese Waechter',
    'Heath Golden',
    'Randy Shoemaker',
    'Seamus Menihane',
    'Jason Richelson',
    'Prashant Shah',
    'Michael C. Martocci',
    'Myrna Aponte',
    'Nipun Seri',
    'Artem Mashkov',
    'Helen Rankin',
    'Jorge Velez',
    'Mariam Garner',
    'Jess R.',
    'Uniqua Couch',
    'Francisco Escobar',
    'Bryan Ramirez',
    'Caitlin Levine',
    'Margaret Johnson',
    'Narin Phol',
    'Nipun Bansal',
    'Puneet Vaid',
    'Alejandra Ospina Rodriguez',
    'Pedro Diaz',
    'Zoe Aumick',
    'Javier Castaneda',
    'Sanjoli Mangat',
    'Karthik Vasudevan',
    'Tiago Paiva',
    'Keven Narrainen',
    'William Thayer',
    'Jordan Morrell',
    'Alan Quach',
    'Lockie Andrews',
    'Dov Moran',
    'Leesa Eichberger',
    'Larry Li',
    'Barry O''Neill',
    'Robin Raskin',
    'Aaron Cordovez',
    'Zach Stuck',
    'Carl Szasz',
    'Michael Moore',
    'Scott Zenker',
    'Abigail Cook Stone',
    'Sierra St. Pierre',
    'Sophia Poppe',
    'Emily Wilmoth',
    'Margaret Steingart',
    'Jeppe Lisdorf',
    'Scott Pattillo',
    'Cameron Gawley',
    'Rico J. Macaraeg',
    'Amber Vitale',
    'Katherine Prime',
    'Liz Edmiston',
    'Mike Gray',
    'Lily Newman',
    'Krista B.',
    'Kerstin Hadzik',
    'Brendan Witcher',
    'Jess Crane',
    'Jeff Streader',
    'Parnell Eagle',
    'Danielle Lafleur',
    'Mo B.',
    'Will McGinn',
    'Ruben Hassid',
    'Sumit Bansal',
    'Alex S.',
    'Seth Spears',
    'Kelly Stacey',
    'Christine Kelley Storch',
    'Michael Clinton',
    'Tim Morgan',
    'Larry Waterman',
    'Brian Dunlap',
    'Peter Kim',
    'Yossi Nasser',
    'Donny Greenberger',
    'Caroline Levy Limpert',
    'David Shamszad',
    'Stephanie Greer',
    'Harper Poe',
    'Benita Singh',
    'Liz Barrere',
    'Scipione B.',
    'Josh Krepon',
    'Colleen Waters',
    'Ben Cogan',
    'Max Starkman',
    'Hasan Lodhi',
    'James Ren',
    'Peyton Bigora',
    'Benjamin Baxter',
    'Kassi Heidenreich',
    'Bradley Ryan C.',
    'Dan Caron',
    'Joe Schaefer',
    'Christopher Heyn',
    'Patty Delgado',
    'Ponch Membreño',
    'Brenna Lyden',
    'Christina Bullock',
    'Eric Hulli',
    'Richard Ginsburg',
    'Gregory Lewis',
    'Terry Kirtley',
    'Anastasia Bottos',
    'Vickie Catina',
    'Aaron Cunningham',
    'Mesh Gelman',
    'Ann Crady Weiss',
    'David Weiss',
    'Katie Kaps',
    'Lauren Berlingeri',
    'Richard Christiansen',
    'Zachary Hill',
    'Taylor McCleneghan',
    'Alex Y.',
    'Gautham Chidambaram',
    'Mitch Brandow',
    'Jesse S.',
    'Daryl Gullickson',
    'Thomas Minieri',
    'Gretta van Riel'
  )
);
